name: SimpleHologram
version: '1.0-SNAPSHOT'
main: org.oxisi.simpleHologram.SimpleHologram
api-version: '1.21'
commands:
  createholo:
    description: Creates a hologram
    usage: "/createholo <id> <text>"
  removeholo:
    description: Removes a hologram
    usage: "/removeholo <id>"
  reloadholo:
    description: Reloads all holograms
    usage: "/reloadholo"